language: ruby

cache: bundler

before_script:
  - bundle exec danger

env:
  - ELASTICSEARCH=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.8.1.deb

before_install:
  - gem update --system
  - gem update bundler
  - curl -O $ELASTICSEARCH && sudo dpkg -i --force-confnew elasticsearch-*.deb
  - sudo systemctl start elasticsearch
  - until curl --silent -XGET --fail http://localhost:9200; do printf '.'; sleep 1; done

rvm:
  - 2.3.1
