language: ruby

cache: bundler

before_script:
  - bundle exec danger

env:
  - ELASTICSEARCH=https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.4.5/elasticsearch-2.4.5.deb
  - ELASTICSEARCH=https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.6.deb

before_install:
  - gem update --system
  - gem update bundler
  - curl -O $ELASTICSEARCH && sudo dpkg -i --force-confnew elasticsearch-*.deb
  - "echo 'script.inline: on' | sudo tee -a /etc/elasticsearch/elasticsearch.yml"
  - sudo /etc/init.d/elasticsearch start
  - until curl --silent -XGET --fail http://localhost:9200; do printf '.'; sleep 1; done

rvm:
  - 2.3.1
