version: 2.1

jobs:
  test:
    docker:
      - image: "cimg/ruby:<< parameters.ruby_version >>"
      - image: "<< parameters.search_image >>"
        environment:
          - discovery.type: single-node
          # the following are ignored by elasticsearch images
          - DISABLE_SECURITY_PLUGIN: "true"
          - DISABLE_INSTALL_DEMO_CONFIG: "true"
          - OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
    parameters:
      ruby_version:
        type: string
      search_image:
        type: string
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Print ruby version
          command: ruby -v
      - run:
          name: Wait for search engine
          command: dockerize -wait tcp://localhost:9200 -timeout 2m
      - run:
          name: Run test suite
          command: bundle exec rake

workflows:
  default:
    jobs:
      - test:
          matrix:
            parameters:
              ruby_version: ["3.1"]
              search_image:
                - "docker.elastic.co/elasticsearch/elasticsearch:7.17.18"
                - "opensearchproject/opensearch:3.3.0"
