version: 2.1

jobs:
  test:
    docker:
      - image: "cimg/ruby:<< parameters.ruby_version >>"
      - image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
        environment:
          - discovery.type: single-node
    parameters:
      ruby_version:
        type: string
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Print ruby version
          command: ruby -v
      - run:
          name: Wait for ElasticSearch
          command: dockerize -wait tcp://localhost:9200 -timeout 1m
      - run:
          name: Run test suite
          command: bundle exec rake

workflows:
  default:
    jobs:
      - test:
          matrix:
            parameters:
              ruby_version: ["3.1"]
